name: Build and deploy Python app with frontend to Azure Web App - webgpt0jdjja

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend setup
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install backend dependencies
        run: |
          python -m venv ./backend/backend_env
          source ./backend/backend_env/bin/activate
          cd backend
          pip install -r requirements.txt

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Update Node.js version if necessary

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      # Zip the deployment artifact
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip . -x "backend_env/*"  # Exclude virtual environment

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for Azure login

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_25C25C486B1C4289A24FAEBB04EE28B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1BDBE70FAB4B49F0AE2AC82B32868D6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAE45DC7CBDA4E44876119AC0A448532 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'webgpt0jdjja'
          slot-name: 'Production'
